"""Posterior summary tables for Bayesian VAR (NIW + Gibbs)."""

import numpy as np
import pandas as pd


def _summarize(draws: np.ndarray) -> dict[str, np.ndarray]:
    draws = np.asarray(draws)
    return {
        "mean": draws.mean(axis=0),
        "sd": draws.std(axis=0),
        "lo": np.quantile(draws, 0.025, axis=0),
        "hi": np.quantile(draws, 0.975, axis=0),
    }


def posterior_bvar_summary(
    B_draws: np.ndarray,
    Sigma_draws: np.ndarray,
    *,
    n: int = 3,
    var_labels: list[str] | None = None,
    reg_labels: list[str] | None = None,
) -> pd.DataFrame:
    """Long-format posterior summaries for intercept, lag-1 block, and Sigma."""
    if var_labels is None:
        var_labels = ["Oil production", "Real activity", "Real oil price"]
    if reg_labels is None:
        reg_labels = [r"$\Delta prod_{t-1}$", r"$rea_{t-1}$", r"$rpo_{t-1}$"]

    rows: list[dict] = []

    s_int = _summarize(B_draws[:, 0, :])
    for j, eq in enumerate(var_labels):
        rows.append(
            {
                "block": "Intercept",
                "equation": eq,
                "parameter": "Constant",
                "mean": s_int["mean"][j],
                "sd": s_int["sd"][j],
                "ci_lo": s_int["lo"][j],
                "ci_hi": s_int["hi"][j],
            }
        )

    lag1 = B_draws[:, 1 : 1 + n, :]
    for j, eq in enumerate(var_labels):
        s_l1 = _summarize(lag1[:, :, j])
        for i, reg in enumerate(reg_labels):
            rows.append(
                {
                    "block": "Lag-1",
                    "equation": eq,
                    "parameter": reg,
                    "mean": s_l1["mean"][i],
                    "sd": s_l1["sd"][i],
                    "ci_lo": s_l1["lo"][i],
                    "ci_hi": s_l1["hi"][i],
                }
            )

    sigma_specs = [
        ("oil supply shock", r"$\Sigma_{11}$", 0, 0),
        ("commodity agg. demand shock", r"$\Sigma_{21}$", 1, 0),
        ("commodity agg. demand shock", r"$\Sigma_{22}$", 1, 1),
        ("oil specific demand shock", r"$\Sigma_{33}$", 2, 2),
        ("oil specific demand shock", r"$\Sigma_{31}$", 2, 0),
        ("oil specific demand shock", r"$\Sigma_{32}$", 2, 1),
    ]
    for equation, name, i, j in sigma_specs:
        s = _summarize(Sigma_draws[:, i, j])
        rows.append(
            {
                "block": "Sigma",
                "equation": equation,
                "parameter": name,
                "mean": float(s["mean"]),
                "sd": float(s["sd"]),
                "ci_lo": float(s["lo"]),
                "ci_hi": float(s["hi"]),
            }
        )

    return pd.DataFrame(rows)


def posterior_bvar_latex(
    summary: pd.DataFrame,
    *,
    caption: str = "Posterior summaries of reduced-form BVAR parameters",
    label: str = "tab:posterior_bvar",
    digits: int = 3,
    notes: str = "",
) -> str:
    """Render summary DataFrame as a booktabs LaTeX table."""

    def fmt(x: float) -> str:
        return f"{x:.{digits}f}"

    block_titles = {
        "Intercept": "\\textit{Intercept}",
        "Lag-1": "\\textit{Lag-1 coefficients}",
        "Sigma": "\\textit{Reduced-form residual covariance $\\Sigma=B_0\\vec{e_t}$}",
    }

    lines = [
        "% Auto-generated by posterior_table.posterior_bvar_latex",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\small",
        "\\begin{tabular}{llcc}",
        "\\toprule",
        "Equation & Regressor & Mean & 95\\% credible interval \\\\",
        "\\midrule",
        f"\\multicolumn{{4}}{{l}}{{{block_titles['Intercept']}}} \\\\",
    ]
    for _, row in summary[summary["block"] == "Intercept"].iterrows():
        ci = f"[{fmt(row['ci_lo'])}, {fmt(row['ci_hi'])}]"
        lines.append(
            f"{row['equation']} & {row['parameter']} & {fmt(row['mean'])} & {ci} \\\\"
        )

    lines.append("\\addlinespace")
    lines.append(f"\\multicolumn{{4}}{{l}}{{{block_titles['Lag-1']}}} \\\\")
    lag_sub = summary[summary["block"] == "Lag-1"]
    for i, (_, row) in enumerate(lag_sub.iterrows()):
        ci = f"[{fmt(row['ci_lo'])}, {fmt(row['ci_hi'])}]"
        lines.append(
            f"{row['equation']} & {row['parameter']} & {fmt(row['mean'])} & {ci} \\\\"
        )
        if (i + 1) % 3 == 0 and i + 1 < len(lag_sub):
            lines.append("\\addlinespace")

    lines.append("\\midrule")
    lines.append(f"\\multicolumn{{4}}{{l}}{{{block_titles['Sigma']}}} \\\\")
    for _, row in summary[summary["block"] == "Sigma"].iterrows():
        ci = f"[{fmt(row['ci_lo'])}, {fmt(row['ci_hi'])}]"
        lines.append(
            f"{row['equation']} & {row['parameter']} & {fmt(row['mean'])} & {ci} \\\\"
        )

    lines += ["\\bottomrule", "\\end{tabular}"]
    if notes:
        lines += [
            "\\begin{minipage}{0.95\\linewidth}",
            f"\\footnotesize {notes}",
            "\\end{minipage}",
        ]
    lines.append("\\end{table}")
    return "\n".join(lines)
