"""Summary tables for Cholesky-identified structural innovations."""

import numpy as np
import pandas as pd
from bvar_helper import structural_shocks_from_bmean


# Row order matches reduced-form Sigma table (Kilian Cholesky ordering)
STRUCTURAL_COV_ROWS = [
    ("oil supply shock", r"$\Sigma_{11}$", 0, 0),
    ("commodity agg. demand shock", r"$\Sigma_{21}$", 1, 0),
    ("commodity agg. demand shock", r"$\Sigma_{22}$", 1, 1),
    ("oil specific demand shock", r"$\Sigma_{33}$", 2, 2),
    ("oil specific demand shock", r"$\Sigma_{31}$", 2, 0),
    ("oil specific demand shock", r"$\Sigma_{32}$", 2, 1),
]


def _summarize(draws: np.ndarray) -> dict[str, float]:
    draws = np.asarray(draws, dtype=float)
    return {
        "mean": float(draws.mean()),
        "ci_lo": float(np.quantile(draws, 0.025)),
        "ci_hi": float(np.quantile(draws, 0.975)),
    }


def structural_innovations_posterior_table(
    y: np.ndarray,
    B_draws: np.ndarray,
    Sigma_draws: np.ndarray,
    *,
    p: int = 24,
    max_draws: int | None = 2000,
) -> pd.DataFrame:
    """Long-format posterior summaries of sample Cov(epsilon) by shock (like Sigma block)."""
    n_keep = B_draws.shape[0]
    if max_draws is not None:
        idx = np.linspace(0, n_keep - 1, min(max_draws, n_keep), dtype=int)
    else:
        idx = np.arange(n_keep)

    element_draws = {(i, j): [] for _, _, i, j in STRUCTURAL_COV_ROWS}

    for d in idx:
        Ehat = structural_shocks_from_bmean(y, B_draws[d], Sigma_draws[d], p=p)
        cov_eps = np.cov(Ehat)
        for _, _, i, j in STRUCTURAL_COV_ROWS:
            element_draws[i, j].append(cov_eps[i, j])

    rows = []
    for equation, parameter, i, j in STRUCTURAL_COV_ROWS:
        s = _summarize(np.array(element_draws[i, j]))
        rows.append(
            {
                "equation": equation,
                "parameter": parameter,
                "mean": s["mean"],
                "ci_lo": s["ci_lo"],
                "ci_hi": s["ci_hi"],
            }
        )
    return pd.DataFrame(rows)


def structural_innovations_latex(
    summary: pd.DataFrame,
    *,
    caption: str = "Posterior summaries of structural innovations",
    label: str = "tab:structural_innovations",
    section_title: str = r"\textit{Structural innovation covariance $\mathrm{Cov}(\varepsilon_t)$}",
    digits: int = 3,
    notes: str = "",
) -> str:
    """Render long-format summary as 4-column booktabs table (Equation, Regressor, Mean, 95% CI)."""

    def fmt(x: float) -> str:
        return f"{x:.{digits}f}"

    lines = [
        "% Auto-generated by structural_shock_table.structural_innovations_latex",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\small",
        "\\begin{tabular}{llcc}",
        "\\toprule",
        "Equation & Regressor & Mean & 95\\% credible interval \\\\",
        "\\midrule",
        f"\\multicolumn{{4}}{{l}}{{{section_title}}} \\\\",
    ]
    for _, row in summary.iterrows():
        ci = f"[{fmt(row['ci_lo'])}, {fmt(row['ci_hi'])}]"
        lines.append(
            f"{row['equation']} & {row['parameter']} & {fmt(row['mean'])} & {ci} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    if notes:
        lines += [
            "\\begin{minipage}{0.95\\linewidth}",
            f"\\footnotesize {notes}",
            "\\end{minipage}",
        ]
    lines.append("\\end{table}")
    return "\n".join(lines)
